---

name : Java with maven
on: 
   push:
    branches: 
      - test 
     
jobs: 
  build:
    name:  "maven" 
    runs-on: ubuntu-24.04
    steps: 
      - name: My first step
        run: mvn package
      - uses: actions/checkout@v4 
        
       



