# ---

# name : Java with maven
# on: 
#    push
 
# jobs: 
#   build:
#     name:  "maven" 
#     runs-on: ubuntu-latest
#     steps: 
#     - uses: actions/setup-java@v2
#       with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#     - uses: actions/checkout@v4
#     - name: My first step
#       run: mvn package
#       working-directory: .


name: Java with Maven

on:
  push:
    branches:
      - main  # Adjust this to your default branch if necessary

jobs:
  build:
    name: "Maven Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      # Step 2: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Run Maven package command
      - name: Build with Maven
        run: mvn clean package
        working-directory: .  # Adjust if your pom.xml is in a subdirectory

