---

name : Java with maven
on: 
   push
 
jobs: 
  build:
    name:  "maven" 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: My first step
        run: mvn package
      - uses: actions/setup-java@v4
        with:
           java-version: '17'
           distribution: 'temurin'
           cache: maven
      - name: Build with Maven
        run: mvn package
